# Generated by Django 4.2 on 2025-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата выхода')),
                ('author', models.CharField(max_length=60, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Заголовк'),
        ),
    ]
